### Section A: Data Structures & Control Structures

1. Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

In [22]:
# Create a list
numbers = [10, 60, 55, 40, 30]

print("Original List:", numbers)

# append()
numbers.append(35)
print("List of numbers after appending: ", numbers)

#extend()
numbers.extend([70, 90])
print("List of numbers after extend: ",numbers)

#insert()
numbers.insert(5, 79)
print("list after insert: ", numbers)

#remove()
numbers.remove(90)
print("List of numbers after remove: ", numbers)

#pop()
numbers.pop()
print("After pop: ", numbers)

#index()
print("Index of 30: ",numbers.index(30))

#count()
print("Count of 60:", numbers.count(60))

#sort()
numbers.sort()
print("Sorted List:", numbers)

#reverse()
numbers.reverse()
print("Reversed list: ", numbers)

#clear()
temp = numbers.copy()
temp.clear()
print("After clear: ", temp)

Original List: [10, 60, 55, 40, 30]
List of numbers after appending:  [10, 60, 55, 40, 30, 35]
List of numbers after extend:  [10, 60, 55, 40, 30, 35, 70, 90]
list after insert:  [10, 60, 55, 40, 30, 79, 35, 70, 90]
List of numbers after remove:  [10, 60, 55, 40, 30, 79, 35, 70]
After pop:  [10, 60, 55, 40, 30, 79, 35]
Index of 30:  4
Count of 60: 1
Sorted List: [10, 30, 35, 40, 55, 60, 79]
Reversed list:  [79, 60, 55, 40, 35, 30, 10]
After clear:  []


2. Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why

In [37]:
# Tuple of student names

students = ("Rahul", "Priya", "Anjali")

print("Original Tuple: ", students)

# Tuples are immutable
try:
    students[1] = "Riya"
except TypeError as e:
    print("Error: ", e)

print("\n Explanation")
print("Tuples are immutable, meaning their elements cannot be changed after creation")

Original Tuple:  ('Rahul', 'Priya', 'Anjali')
Error:  'tuple' object does not support item assignment

 Explanation
Tuples are immutable, meaning their elements cannot be changed after creation


3. Create a set of integers with some duplicate values. Print the set and explain the output.

In [35]:
integers = {1, 2, 4, 5, 7, 4, 3, 6, 3}

print("Set: ", integers)

print("\n Explanation: ")
print("Sets automatically remove duplicate values")

Set:  {1, 2, 3, 4, 5, 6, 7}

 Explanation: 
Sets automatically remove duplicate values


4. Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.

In [34]:
person = {
    "name" : "Siya",
    "age" : 22,
    "city" : "Pune"
}

person["age"] = 23

person["email"] = "siya643@gmail.com"

print("Updated Dictionary: ")
print(person)

Updated Dictionary: 
{'name': 'Siya', 'age': 23, 'city': 'Pune', 'email': 'siya643@gmail.com'}


5. Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.

In [24]:
age = 20

if age >= 18:
    print("The person is eligible to vote")
else:
    print("The person is not eligible to vote ")

The person is eligible to vote


6. Given a 'marks' variable, print the grade: - 90 and above: 'A' - 75–89: 'B' - 50–74: 'C' - Below 50: 'Fail'

In [29]:
marks = int(input("Enter the marks"))
if marks >= 90:
    res = 'Grade: A'
elif marks >= 75 and marks <= 89:
    res = 'Grade: B'
elif marks >= 50 and marks <= 74:
    res = 'Grade: C'
else:
    res = 'Fail'
print(res)

Enter the marks 98


Grade: A


7. Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [32]:
number = int(input("Enter a number"))

if number > 0:
    print ("Positive number")

    if number % 2 == 0:
        print("It is a Even number")
    else:
        print("It is a Odd number")

elif number == 0:
    print("It is zero")

else:
    print("It is a negative number")

Enter a number -6


It is a negative number


### Section B: Numpy

8. Create: - A scalar using np.array(5) - A 1D array with values 1 to 5 - A 2D array (2x3) with values from 10 to 60 in steps of 10

In [6]:
import numpy as np

scalar = np.array(5)
print("scalar: ", scalar)

# 1D array
array1 = np.array([1,2,3,4,5])
print("\n 1D array: ", array1)

# 2D array
array2 = np.array([10, 20, 30, 40, 50, 60])
print("\n 2D array: ", array2)

scalar:  5

 1D array:  [1 2 3 4 5]

 2D array:  [10 20 30 40 50 60]


9. Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [8]:
random_array = np.random.randint(0, 101, size=(4,4))

print("Random Array: ")
print(random_array)

Random Array: 
[[92 91 82 93]
 [92 36 68 16]
 [12 48 56 31]
 [95 13 36 50]]


10. Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [11]:
import numpy as np
import pandas as pd

# 3X3 NumPy array
arr = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])

# Convert to DataFrame
df = pd.DataFrame(arr, columns=["A", "B", "C"])
print(df)

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9


### Section C: Exploring Pandas

11. Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then: - Use .info(), .describe() - Select 'Name' and 'City' columns - Drop 'City' column - Fill any missing values in 'Salary' column with the mean - Remove any duplicate rows

In [17]:
# Create DataFrame
data = {
    "Name" : ["Anita", "Rahul", "Priya", "Kiran", "Siya", "Sneha", "Anita","Ravi", "Vijay", "Rohan"],
    "Age" : [22, 25, 21, 24, 23, 26, 28, 22, 27, 25],
    "City" : ["Belagavi", "Bengaluru", "Hubli", "Mysuru", "Dharwad", "Belagavi", "Pune", "Hubli","Mysuru", "Bengaluru"],
    "Salary" : [25000, 35000, np.nan, 42000, 30000, 45000, 50000, np.nan, 38000, 35000]
}

df = pd.DataFrame(data)

# Add duplicate row
df.loc[10] = df.loc[1]

print("Original DataFrame: ", df)

print("\n DataFrame Info: ")
print(df.info())

print("\n DataFrame Description: ")
print(df.describe())

print("\n Select Name and City: ")
print(df[["Name", "City"]])

# Drop City Column
df_drop = df.drop(columns=["City"])

print("\n After Dropping City: ")
print(df_drop)

df["Salary"] = df["Salary"].fillna(df["Salary"].mean())

print("\n After Filling Missing Salary: ")
print(df)

# Remove duplicate rows
df = df.drop_duplicates()

print("\n After Removing Duplicate Rows: ")
print(df)

Original DataFrame:       Name  Age       City   Salary
0   Anita   22   Belagavi  25000.0
1   Rahul   25  Bengaluru  35000.0
2   Priya   21      Hubli      NaN
3   Kiran   24     Mysuru  42000.0
4    Siya   23    Dharwad  30000.0
5   Sneha   26   Belagavi  45000.0
6   Anita   28       Pune  50000.0
7    Ravi   22      Hubli      NaN
8   Vijay   27     Mysuru  38000.0
9   Rohan   25  Bengaluru  35000.0
10  Rahul   25  Bengaluru  35000.0

 DataFrame Info: 
<class 'pandas.core.frame.DataFrame'>
Index: 11 entries, 0 to 10
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    11 non-null     object 
 1   Age     11 non-null     int64  
 2   City    11 non-null     object 
 3   Salary  9 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 440.0+ bytes
None

 DataFrame Description: 
             Age        Salary
count  11.000000      9.000000
mean   24.363636  37222.222222
std     2.203303   7612.124831